#!/usr/bin/python3
import sys

def factorize_number(n):
    """
    Function to factorize a number into a product of two smaller numbers.
    """
    if n % 2 == 0:
        print("{}={}*{}".format(n, n // 2, 2))
    else:
        i = 3
        while i <= n // 2:
            if n % i == 0:
                print("{}={}*{}".format(n, n // i, i))
                break
            i += 2
        else:  # Executed when the while loop completes without hitting the 'break' statement
            print("{}={}*{}".format(n, n, 1))

def factorize_file(file_path):
    """
    Function to factorize numbers from a file.
    """
    try:
        with open(file_path) as f:
            for line in f:
                number = int(line)
                factorize_number(number)
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
    except ValueError:
        print("Invalid input. Please ensure all lines contain valid natural numbers.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
    else:
        factorize_file(sys.argv[1])
